version: '3'  

services:     
  laravel-app:                                                                                                                                   
    build: .                                                                                                                                 
    ports:                                                                           
      - 8080:80                                                                  
    volumes:
      - ./:/usr/share/nginx
    networks:
      - app-network

  mysql-app:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    ports:
      - "3308:3309"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: crud-api
      MYSQL_ROOT_PASSWORD: miau
    networks:
      - app-network  
networks:
  app-network:
    driver: bridge